#!/usr/bin/env bash
# org-core: role=org file=setup base=0.31.5 — generated by `org apply` from org.yaml (ports + suite:); do not edit — the input is the manifest
# The suite install for the switchboard org (org-core SPEC §18): every module its ports need, installed by
# version, one report at the end. Runs first on every SessionStart (.claude/settings.json). Never fails a
# session: each module logs what it did or why it could not, and the report says what this container has.
set -uo pipefail
log() { echo "[org-setup] $*" >&2; }

# cloud only — a local machine manages its own Python environment (suite.cloud_only: false to run everywhere)
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then exit 0; fi

REPO="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
TMP="${TMPDIR:-/tmp}"
REPORT="$TMP/org-setup-report.json"
INSTALLED=""
FAILED=""
note_ok() { INSTALLED="$INSTALLED $1"; log "$1: $2"; }
note_fail() { FAILED="$FAILED $1"; log "$1: $2"; }
pipi() { python3 -m pip install --quiet --break-system-packages "$@" || python3 -m pip install --quiet "$@"; }
pyver() { python3 -c 'import importlib.metadata as m, sys; print(m.version(sys.argv[1]))' "$1" 2>/dev/null || echo none; }

# ---- org-core (vendored) ----

# org-core: install by version — the newest org-core wheel this container can see, the checkout's or origin/main's,
# installed whenever its version differs from the org-core on PATH (SPEC Appendix A rows 54, 87, 88).
# Never gate this on `command -v org`: a restarted persistent session keeps the binary its first container
# installed (row 87). And a persistent session lives on its own branch, whose hook and wheel can be days
# behind main — so main's wheel is read too and the newer of the two wins (row 88, Marshal 2026-09-20).
REPO="${CLAUDE_PROJECT_DIR:-${REPO:-.}}"
WHEEL="$(ls "$REPO"/.org/wheels/org_core-*-py3-none-any.whl 2>/dev/null | sort -V | tail -n 1)"
MAIN_WHEEL="$(git -C "$REPO" fetch -q origin main 2>/dev/null; git -C "$REPO" ls-tree -r --name-only origin/main -- .org/wheels/ 2>/dev/null | grep -E 'org_core-.*-py3-none-any\.whl$' | sort -V | tail -n 1)"
if [ -n "$MAIN_WHEEL" ] && [ "$(basename "$MAIN_WHEEL")" != "$(basename "$WHEEL")" ] \
   && [ "$(printf '%s\n%s\n' "$(basename "$WHEEL")" "$(basename "$MAIN_WHEEL")" | sort -V | tail -n 1)" = "$(basename "$MAIN_WHEEL")" ]; then
  mkdir -p /tmp/org-core-wheels && git -C "$REPO" show "origin/main:$MAIN_WHEEL" > "/tmp/org-core-wheels/$(basename "$MAIN_WHEEL")" 2>/dev/null \
    && WHEEL="/tmp/org-core-wheels/$(basename "$MAIN_WHEEL")" && log "org-core: origin/main vendors $(basename "$MAIN_WHEEL"), newer than this branch's"
fi
# The package's OWN repository is the one place the wheel must not be installed: there the source IS the package,
# and the moment the source moves past the vendored wheel the test below — a plain inequality, deliberately, so a
# stale container is corrected in either direction (rows 87, 88) — would install the OLDER wheel over it and
# downgrade the builder. Found by installing org-core into itself, 2026-09-22. But nothing else puts the checkout
# on PATH either: measured 2026-09-23 on main at ceb07c5 (0.31.3), a fresh container ran `org` 0.29.1, the hook
# logged "the checkout on PATH is the truth" and installed nothing, and the report read org-core ok. So here the
# checkout is installed editable whenever its version differs from the org-core on PATH.
if [ -f "$REPO/pyproject.toml" ] && grep -qE '^name = "org-core"' "$REPO/pyproject.toml" 2>/dev/null; then
  WANT="$(sed -nE 's/^__version__ = "([^"]+)".*/\1/p' "$REPO/org_core/__init__.py" 2>/dev/null | head -n 1)"
  HAVE="$(org --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n 1)"
  if [ "$HAVE" != "$WANT" ]; then
    python3 -m pip install --quiet --break-system-packages -e "$REPO" 2>/tmp/org-core-install.err \
      && log "org-core: this repo is the package — ${HAVE:-none} -> $WANT, the checkout installed editable" \
      || log "org-core: editable install of the checkout failed: $(tail -3 /tmp/org-core-install.err | tr '\n' ' ')"
  else
    log "org-core: this repo is the package — $WANT on PATH matches the checkout"
  fi
elif [ -n "$WHEEL" ]; then
  WANT="$(basename "$WHEEL" | sed -E 's/^org_core-([0-9][0-9.]*)-.*/\1/')"
  HAVE="$(org --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n 1)"
  if [ "$HAVE" != "$WANT" ]; then
    python3 -m pip install --quiet --break-system-packages "$WHEEL" 2>/tmp/org-core-install.err \
      && log "org-core ${HAVE:-none} -> $WANT from $(basename "$WHEEL")" \
      || log "org-core install from $WHEEL failed: $(tail -3 /tmp/org-core-install.err | tr '\n' ' ')"
  fi
else
  log "no vendored org-core wheel under .org/wheels/ — run \`org vendor --repo .\` from a session that holds org-core"
fi
# The version the install above aimed at, for the report: a vendored module is ok only when `org --version` is it.
export ORG_CORE_WANT="${WANT:-}"
command -v org >/dev/null 2>&1 || note_fail org-core "not on PATH after the install above"

# ---- switchboard (tracking, the coordination port) ----

# tracking: PyPI's current release, unpinned — a stale client against a newer hub fails silently (an agent lands in the
# wrong room or none, and an empty inbox reads as a quiet one; Lucille 2026-08-31). Installed when absent; upgraded once a day.
ERR="$TMP/org-setup-switchboard.err"; STAMP="$TMP/org-setup-switchboard.upgraded"
if [ "$(pyver agent-switchboard)" = "none" ] || ! command -v switchboard >/dev/null 2>&1; then
  if pipi --ignore-installed cryptography 'agent-switchboard[all]' 2>"$ERR"; then
    touch "$STAMP"; note_ok switchboard "installed $(pyver agent-switchboard)"
  else
    note_fail switchboard "install failed: $(tail -3 "$ERR" | tr '\n' ' ')"
  fi

  python3 -c "import cffi" >/dev/null 2>&1 || pipi --force-reinstall cffi >/dev/null 2>&1 || true

elif [ -z "$(find "$STAMP" -mmin -1440 2>/dev/null)" ]; then
  BEFORE="$(pyver agent-switchboard)"
  if pipi --upgrade 'agent-switchboard[all]' 2>"$ERR"; then
    touch "$STAMP"; AFTER="$(pyver agent-switchboard)"
    [ "$BEFORE" != "$AFTER" ] && note_ok switchboard "upgraded $BEFORE -> $AFTER"
  else
    note_fail switchboard "upgrade failed (kept $BEFORE): $(tail -3 "$ERR" | tr '\n' ' ')"
  fi
fi

export SWITCHBOARD_URL='https://switchboard.lucille-ai.com'
echo "export SWITCHBOARD_URL='https://switchboard.lucille-ai.com'" >> "${CLAUDE_ENV_FILE:-/dev/null}" 2>/dev/null || true

export SWITCHBOARD_WORKSPACE='gald33/switchboard'
echo "export SWITCHBOARD_WORKSPACE='gald33/switchboard'" >> "${CLAUDE_ENV_FILE:-/dev/null}" 2>/dev/null || true

if command -v switchboard >/dev/null 2>&1; then
  switchboard -q register -c build >/dev/null 2>&1 || log "switchboard register failed (hub unreachable?) — presence is off; records may still write"
fi

# ---- roadmap-core (pinned, the work_store port) ----

# pinned: pip is the comparator — a satisfied requirement is a no-op (no network), one outside the range reinstalls
# (Lucille 2026-09-19: an import-only check kept roadmap-core 0.2.3 under a >=0.3.1 pin, and `diff` could not see `verifying`)
ERR="$TMP/org-setup-roadmap-core.err"
BEFORE="$(pyver roadmap-core)"
if pipi 'roadmap-core[files]>=0.3.1,<0.4' 2>"$ERR"; then
  AFTER="$(pyver roadmap-core)"
  [ "$BEFORE" != "$AFTER" ] && note_ok roadmap-core "$BEFORE -> $AFTER (roadmap-core[files]>=0.3.1,<0.4)"
else
  note_fail roadmap-core "install of 'roadmap-core[files]>=0.3.1,<0.4' failed (have $BEFORE): $(tail -3 "$ERR" | tr '\n' ' ')"
fi

export ROADMAP_SOURCE='local'
echo "export ROADMAP_SOURCE='local'" >> "${CLAUDE_ENV_FILE:-/dev/null}" 2>/dev/null || true

# ---- repoctx (pinned, the code_context port) ----

# pinned: pip is the comparator — a satisfied requirement is a no-op (no network), one outside the range reinstalls
# (Lucille 2026-09-19: an import-only check kept roadmap-core 0.2.3 under a >=0.3.1 pin, and `diff` could not see `verifying`)
ERR="$TMP/org-setup-repoctx.err"
BEFORE="$(pyver repoctx-mcp)"
if pipi 'repoctx-mcp>=1.6' 2>"$ERR"; then
  AFTER="$(pyver repoctx-mcp)"
  [ "$BEFORE" != "$AFTER" ] && note_ok repoctx "$BEFORE -> $AFTER (repoctx-mcp>=1.6)"
else
  note_fail repoctx "install of 'repoctx-mcp>=1.6' failed (have $BEFORE): $(tail -3 "$ERR" | tr '\n' ' ')"
fi

# ---- tickets (builtin, the tickets port) ----

# builtin: inside org-core (`org tickets`) — nothing to install; enabled by the tickets port

# ---- db (service, the prod_read port) ----

# service: readonly-key: the hub at https://switchboard.lucille-ai.com, read with a read-only key from $SWITCHBOARD_READ_KEY (never the write key) — reached through the prod_read port, never installed here; the doctor's check 6 probes it

# ---- gh (external, the vcs port) ----

# external: the environment or this org's own scripts provide it; the suite only reports it
command -v gh >/dev/null 2>&1 || note_fail gh "not on PATH — the vcs port has no shell path in this session"

# ---- the report: what this container has, for `org setup status` and every role's record (doctor check 21) ----
python3 - "$REPORT" "$INSTALLED" "$FAILED" <<'PY' || log "report not written"
import datetime, importlib.metadata as md, json, os, re, shutil, subprocess, sys
MODULES = json.loads(r'''[{"name": "org-core", "policy": "vendored", "dist": "org-core", "cli": "org", "mcp": null, "spec": null}, {"name": "switchboard", "policy": "tracking", "dist": "agent-switchboard", "cli": "switchboard", "mcp": "switchboard", "spec": "agent-switchboard[all]"}, {"name": "roadmap-core", "policy": "pinned", "dist": "roadmap-core", "cli": "roadmap", "mcp": "roadmap", "spec": "roadmap-core[files]>=0.3.1,<0.4"}, {"name": "repoctx", "policy": "pinned", "dist": "repoctx-mcp", "cli": "repoctx", "mcp": "repoctx", "spec": "repoctx-mcp>=1.6"}, {"name": "tickets", "policy": "builtin", "dist": null, "cli": null, "mcp": null, "spec": null}, {"name": "db", "policy": "service", "dist": null, "cli": null, "mcp": null, "spec": null}, {"name": "gh", "policy": "external", "dist": null, "cli": "gh", "mcp": null, "spec": null}]''')
out, installed, failed = sys.argv[1], sys.argv[2].split(), sys.argv[3].split()
def dist_version(d):
    try:
        return md.version(d)
    except Exception:
        return None
def cli_version(c):
    if not c or not shutil.which(c):
        return None
    try:
        p = subprocess.run([c, "--version"], capture_output=True, text=True, timeout=20)
        m = re.search(r"\d+(\.\d+)+", (p.stdout or "") + (p.stderr or ""))
        return m.group(0) if m else "present"
    except Exception:
        return "present"
rep = {"at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"), "org_core": None, "modules": {}, "installed": installed, "failed": failed}
for m in MODULES:
    pol, cli = m["policy"], m.get("cli")
    on_path = bool(cli) and shutil.which(cli) is not None
    if pol == "vendored":
        v = cli_version(cli) or dist_version(m.get("dist"))     # what the hook compared: `org --version`
        want = os.environ.get("ORG_CORE_WANT") or None         # the version the hook installed toward
        # present is not installed: 0.29.1 on PATH read ok against a 0.31.3 checkout (2026-09-23)
        ok = v is not None and on_path and m["name"] not in failed and (want is None or v == want)
    elif pol in ("pinned", "tracking"):
        v = dist_version(m.get("dist"))
        ok = v is not None and (on_path or not cli) and m["name"] not in failed
    elif pol == "external":
        v = cli_version(cli)
        ok = on_path
    elif pol == "builtin":
        v = dist_version("org-core")
        ok = v is not None
    else:
        v, ok = None, None
    rep["modules"][m["name"]] = {"policy": pol, "version": v, "ok": ok, "cli": cli, "on_path": on_path, "spec": m.get("spec")}
    if pol == "vendored":
        rep["modules"][m["name"]]["want"] = want
rep["org_core"] = (rep["modules"].get("org-core") or {}).get("version")
with open(out, "w") as fh:
    json.dump(rep, fh, indent=1)
print("[org-setup] " + ", ".join(f"{n} {m['version'] or '-'}" for n, m in rep["modules"].items() if m["policy"] not in ("builtin", "service"))
      + ("; FAILED: " + " ".join(failed) if failed else ""), file=sys.stderr)
PY
exit 0
